site_name: Reacton
theme:
  name: material
repo_url: https://github.com/widgetti/reacton/

nav:
  - index.md
  - installing.md
  - getting-started.md
  - examples.md
  - API: api.md
  - understanding.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  analytics:
    provider: google
    property: UA-240047566-1
