name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - mkdocs
  - mkdocs-material
  - mamba
  - empack

  - pip:
      - jupyterlite
      - jupyterlite-sphinx
      - jupyterlite-xeus-python
      - jupyterlab-night
      - jupyterlab_google_analytics
