name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install hatch
        run: pip install hatch "pip<22"
      - name: Install
        run: hatch install
      - name: Uninstall
        run: pip uninstall react_ipywidgets -y
      - name: Build
        run: hatch build
      - name: Install
        run: pip install dist/*.whl
      - name: Test import
        run: python -c "import react_ipywidgets"
      - name: Publish a Python distribution to PyPI
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.pypi_password }}
        run: |
          openssl sha256 dist/*
          hatch publish
      - uses: actions/upload-artifact@v1
        with:
          name: distributions
          path: ./dist
